// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTqYt_MZgsWa9Cini2gjMfLPOS2u9_lTA',
    appId: '1:50440651042:web:761c821fd0cc8751c4657b',
    messagingSenderId: '50440651042',
    projectId: 'food-helper-32267',
    authDomain: 'food-helper-32267.firebaseapp.com',
    storageBucket: 'food-helper-32267.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlW7Bmxgm3BrKuXZqr32sUVkwDGqU6BWc',
    appId: '1:50440651042:android:9e8f786acf255551c4657b',
    messagingSenderId: '50440651042',
    projectId: 'food-helper-32267',
    storageBucket: 'food-helper-32267.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDey_Az_W-WlYIE7BhkZyIy1LliEHPbD6I',
    appId: '1:50440651042:ios:9505727343c5385bc4657b',
    messagingSenderId: '50440651042',
    projectId: 'food-helper-32267',
    storageBucket: 'food-helper-32267.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDey_Az_W-WlYIE7BhkZyIy1LliEHPbD6I',
    appId: '1:50440651042:ios:9505727343c5385bc4657b',
    messagingSenderId: '50440651042',
    projectId: 'food-helper-32267',
    storageBucket: 'food-helper-32267.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTqYt_MZgsWa9Cini2gjMfLPOS2u9_lTA',
    appId: '1:50440651042:web:ded8ed401da7af9ec4657b',
    messagingSenderId: '50440651042',
    projectId: 'food-helper-32267',
    authDomain: 'food-helper-32267.firebaseapp.com',
    storageBucket: 'food-helper-32267.firebasestorage.app',
  );

}